Rendering universities list using API - universitiesPage
GSG-CF04/UniGuide pull request #32
Opened 2021-12-04 15:29 UTC by nadabassam

Relates #30

2021-12-05 07:57 UTC, basillubbad approved these changes

2021-12-05 10:44 UTC, yaqootturman requested changes

2021-12-05 10:44 UTC, yaqootturman commented on universitiesPage/universities.css
> +#btn-card {
It should take the content size, or fixed-size but bigger

2021-12-07 06:57 UTC, yaqootturman approved these changes

2021-12-07 07:05 UTC, Yousef-Dall approved these changes

2021-12-07 07:09 UTC, merged