Rendering general info of the country
GSG-CF04/UniGuide pull request #33
Opened 2021-12-04 22:40 UTC by basillubbad

Relates #29

2021-12-04 23:24 UTC, nadabassam approved these changes

2021-12-05 10:51 UTC, yaqootturman requested changes

2021-12-05 10:51 UTC, yaqootturman commented on generalInfoPage/general.css
> +.menuIcon {
can't use two different convention for naming in same time and same file
change it to be .menu-icon

2021-12-05 10:51 UTC, yaqootturman commented on generalInfoPage/general.html
> +    <title>Document</title>
the title should describe the page

2021-12-05 22:09 UTC, closed without merging